import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Nav/Navbar";
import RightBar from "@/components/RightBar/RightBar";
import LeftBar from "@/components/LeftBar/LeftBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-[#fff] 2xl:bg-[#F0F2F5]`}>
        {/* <Navbar />
        <RightBar />
        <LeftBar /> */}
        <div className=' 2xl:ml-[560px] ml-[230px] mt-[75px] mr-[95px]'>
          {children}
        </div>
      </body>
    </html>
  );
}
