import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stories",
  description: "Generated by create next app",
};

const layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className={`${inter.className} `}>
        {children}
        <div className='absolute top-0 right-0 left-0 bottom-0 bg-[#1A1A1A]' />
      </body>
    </html>
  );
};

export default layout;
